version: '3.8'

services:
  db:
    image: postgres
    container_name: assessment-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assessment
    ports:
      - "5434:5432"
    volumes:
      - /Users/mallikaroy/gitlearn/assessment_volume:/var/lib/postgresql/data
  app:
    build: .
    image: assessment-app
    container_name: assessment-app-cont
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/assessment
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
